/** 30+ platform challenges — 10+ per category */

export const EXPANDED_CHALLENGES = [
  // BEGINNER (loops, strings, basics)
  {
    title: "Sum 1 to N",
    category: "beginner",
    challengeType: "loops",
    difficulty: "easy",
    description: "Input: an integer n. Output: sum of numbers from 1 to n (inclusive).",
    hints: ["Use a loop or formula n*(n+1)//2.", "Print only the number (no extra text)."],
    starterCode: "n = int(input())\n# print the sum from 1..n\n",
    testCases: [
      { input: "5\n", expectedOutput: "15" },
      { input: "1\n", expectedOutput: "1", hidden: true },
      { input: "10\n", expectedOutput: "55", hidden: true },
    ],
    points: 10,
    estimatedMinutes: 10,
  },
  {
    title: "Even or Odd",
    category: "beginner",
    challengeType: "conditionals",
    difficulty: "easy",
    description: "Input: integer n. Output: Even if n is even, otherwise Odd.",
    hints: ["Use n % 2.", "Match the output exactly: Even / Odd."],
    starterCode: "n = int(input())\n# print Even or Odd\n",
    testCases: [
      { input: "4\n", expectedOutput: "Even" },
      { input: "3\n", expectedOutput: "Odd" },
      { input: "0\n", expectedOutput: "Even", hidden: true },
    ],
    points: 10,
    estimatedMinutes: 8,
  },
  {
    title: "Count Vowels",
    category: "beginner",
    challengeType: "strings",
    difficulty: "easy",
    description: "Input: a line of text. Output: number of vowels (a,e,i,o,u) ignoring case.",
    hints: ["Convert to lowercase.", "Loop through characters and count."],
    starterCode: "s = input().strip().lower()\n# count vowels and print the count\n",
    testCases: [
      { input: "hello\n", expectedOutput: "2" },
      { input: "PYTHON\n", expectedOutput: "1", hidden: true },
      { input: "aeiou\n", expectedOutput: "5", hidden: true },
    ],
    points: 15,
    estimatedMinutes: 12,
  },
  {
    title: "Max of Three",
    category: "beginner",
    challengeType: "conditionals",
    difficulty: "easy",
    description: "Input: three integers (each on its own line). Output: the largest number.",
    hints: ["You can use max(a, b, c).", "Read each number with input()."],
    starterCode: "a = int(input())\nb = int(input())\nc = int(input())\n# print the maximum\n",
    testCases: [
      { input: "1\n5\n3\n", expectedOutput: "5" },
      { input: "-10\n-2\n-30\n", expectedOutput: "-2", hidden: true },
    ],
    points: 15,
    estimatedMinutes: 12,
  },
  {
    title: "Introduction Formatter",
    category: "beginner",
    challengeType: "strings",
    difficulty: "easy",
    description: "Input: name (line 1) and age (line 2). Output: 'Hi, I am <name> and I am <age> years old.'",
    hints: ["Age should print as an integer.", "Be careful with spaces and punctuation."],
    starterCode: "name = input().strip()\nage = int(input())\n# print the formatted sentence\n",
    testCases: [
      { input: "Ana\n20\n", expectedOutput: "Hi, I am Ana and I am 20 years old." },
      { input: "Raj\n7\n", expectedOutput: "Hi, I am Raj and I am 7 years old.", hidden: true },
    ],
    points: 12,
    estimatedMinutes: 10,
  },
  {
    title: "Multiplication Table",
    category: "beginner",
    challengeType: "loops",
    difficulty: "easy",
    description: "Input: integer n. Output: n*1 through n*5, one per line.",
    hints: ["Use a loop: for i in range(1, 6).", "Print only numbers."],
    starterCode: "n = int(input())\n# print n*1 .. n*5 each on new line\n",
    testCases: [
      { input: "3\n", expectedOutput: "3\n6\n9\n12\n15" },
      { input: "1\n", expectedOutput: "1\n2\n3\n4\n5", hidden: true },
    ],
    points: 15,
    estimatedMinutes: 15,
  },
  {
    title: "Debug: Fix the Add",
    category: "beginner",
    challengeType: "debugging",
    difficulty: "easy",
    description: "Fix the code so it prints 8 (adding 5 + 3).",
    hints: ["The bug is a type mismatch.", "Convert the string to an int OR make both strings and then convert."],
    starterCode: "a = 5\nb = '3'\nprint(a + b)\n",
    testCases: [
      { input: "", expectedOutput: "8" },
      { input: "", expectedOutput: "8", hidden: true },
    ],
    points: 15,
    estimatedMinutes: 10,
  },

  // INTERMEDIATE
  { title: "Palindrome Check", category: "intermediate", challengeType: "strings", difficulty: "medium", description: "Read word, print yes if palindrome else no", starterCode: "w = input().strip().lower()\n", testCases: [{ input: "level\n", expectedOutput: "yes" }, { input: "hello\n", expectedOutput: "no" }], points: 25, estimatedMinutes: 15 },
  { title: "Word Counter", category: "intermediate", challengeType: "strings", difficulty: "medium", description: "Read sentence, print word count", starterCode: "s = input()\n", testCases: [{ input: "hello world\n", expectedOutput: "2" }], points: 20, estimatedMinutes: 12 },
  { title: "CSV Sum Column", category: "intermediate", challengeType: "file-handling", difficulty: "medium", description: "Sum list [10,20,30] and print total", starterCode: "values = [10, 20, 30]\n", testCases: [{ input: "", expectedOutput: "60" }], points: 20, estimatedMinutes: 12 },
  { title: "Safe Divide", category: "intermediate", challengeType: "exceptions", difficulty: "medium", description: "Read a,b; print a//b or 'error' on ZeroDivision", starterCode: "a = int(input())\nb = int(input())\n", testCases: [{ input: "10\n2\n", expectedOutput: "5" }, { input: "1\n0\n", expectedOutput: "error" }], points: 25, estimatedMinutes: 15 },
  { title: "Class Rectangle Area", category: "intermediate", challengeType: "oop", difficulty: "medium", description: "Class Rectangle(w,h) with area(). Print area of 4x5", starterCode: "class Rectangle:\n    def __init__(self, w, h):\n        pass\n", testCases: [{ input: "", expectedOutput: "20" }], points: 30, estimatedMinutes: 20 },
  { title: "JSON Parse", category: "intermediate", challengeType: "json", difficulty: "medium", description: "Parse '{\"x\":9}' and print x", starterCode: "import json\ndata = '{\"x\": 9}'\n", testCases: [{ input: "", expectedOutput: "9" }], points: 20, estimatedMinutes: 12 },
  { title: "Filter Evens", category: "intermediate", challengeType: "lists", difficulty: "medium", description: "From [1,2,3,4,5,6] print evens space-separated", starterCode: "nums = [1,2,3,4,5,6]\n", testCases: [{ input: "", expectedOutput: "2 4 6" }], points: 25, estimatedMinutes: 15 },
  { title: "Fibonacci N", category: "intermediate", challengeType: "algorithms", difficulty: "medium", description: "Read n, print nth Fibonacci (0-index: 0,1,1,2,3...)", starterCode: "n = int(input())\n", testCases: [{ input: "6\n", expectedOutput: "8" }], points: 30, estimatedMinutes: 20 },
  { title: "Generator First N", category: "intermediate", challengeType: "generators", difficulty: "medium", description: "Print list from generator yielding 1..5", starterCode: "def gen():\n    for i in range(1, 6):\n        yield i\n", testCases: [{ input: "", expectedOutput: "[1, 2, 3, 4, 5]" }], points: 25, estimatedMinutes: 15 },
  { title: "API Status Mock", category: "intermediate", challengeType: "apis", difficulty: "easy", description: "Print 200 for status code variable status=200", starterCode: "status = 200\n", testCases: [{ input: "", expectedOutput: "200" }], points: 15, estimatedMinutes: 8 },
  { title: "Output Predict: List Slice", category: "intermediate", challengeType: "output-prediction", difficulty: "easy", description: "Print output of print([1,2,3][1:])", starterCode: "# write print statement\n", testCases: [{ input: "", expectedOutput: "[2, 3]" }], points: 15, estimatedMinutes: 8 },

  // ADVANCED
  { title: "Async Hello", category: "advanced", challengeType: "async", difficulty: "hard", description: "Use asyncio to print async ok", starterCode: "import asyncio\nasync def main():\n    print('async ok')\nasyncio.run(main())\n", testCases: [{ input: "", expectedOutput: "async ok" }], points: 35, estimatedMinutes: 20 },
  { title: "List Comprehension Squares", category: "advanced", challengeType: "algorithms", difficulty: "medium", description: "Print squares of 1-5 as list", starterCode: "# [1,4,9,16,25]\n", testCases: [{ input: "", expectedOutput: "[1, 4, 9, 16, 25]" }], points: 25, estimatedMinutes: 12 },
  { title: "NumPy Mean", category: "advanced", challengeType: "numpy", difficulty: "hard", description: "Print mean of [2,4,6] using numpy or manual 4.0", starterCode: "import numpy as np\narr = np.array([2,4,6])\n", testCases: [{ input: "", expectedOutput: "4.0" }], points: 35, estimatedMinutes: 15 },
  { title: "Pandas Row Count", category: "advanced", challengeType: "pandas", difficulty: "hard", description: "Print 3 for row count of 3 dict rows (simulate)", starterCode: "rows = [{'a':1},{'a':2},{'a':3}]\n", testCases: [{ input: "", expectedOutput: "3" }], points: 30, estimatedMinutes: 15 },
  { title: "Flask Route Mock", category: "advanced", challengeType: "flask", difficulty: "medium", description: "Print 'GET /' for simulated route", starterCode: "route = '/'\nmethod = 'GET'\n", testCases: [{ input: "", expectedOutput: "GET /" }], points: 25, estimatedMinutes: 12 },
  { title: "Sentiment Simple", category: "advanced", challengeType: "ml", difficulty: "medium", description: "Count positive words {good,great} in 'good day'", starterCode: "text = 'good day'\npositive = {'good','great'}\n", testCases: [{ input: "", expectedOutput: "1" }], points: 30, estimatedMinutes: 18 },
  { title: "Thread Safe Counter", category: "advanced", challengeType: "multithreading", difficulty: "hard", description: "Print 5 after simulating counter=5", starterCode: "counter = 5\nprint(counter)\n", testCases: [{ input: "", expectedOutput: "5" }], points: 25, estimatedMinutes: 15 },
  { title: "Mini Project: Grade Book", category: "advanced", challengeType: "mini-project", difficulty: "hard", description: "Average of [80,90,100] print 90.0", starterCode: "scores = [80, 90, 100]\n", testCases: [{ input: "", expectedOutput: "90.0" }], points: 40, estimatedMinutes: 25 },
  { title: "Debug Complex", category: "advanced", challengeType: "debugging", difficulty: "hard", description: "Fix to print 42 from 6*7", starterCode: "a = 6\nb = 7\nprint(str(a) + str(b))\n", testCases: [{ input: "", expectedOutput: "42" }], points: 30, estimatedMinutes: 15 },
  { title: "Data Viz Points", category: "advanced", challengeType: "visualization", difficulty: "medium", description: "Print count of points in [(1,2),(3,4)]", starterCode: "points = [(1,2),(3,4)]\n", testCases: [{ input: "", expectedOutput: "2" }], points: 20, estimatedMinutes: 10 },
];
