/** 30+ platform challenges — 10+ per category */

export const EXPANDED_CHALLENGES = [
  // BEGINNER (loops, strings, basics)
  { title: "Sum 1 to N", category: "beginner", challengeType: "loops", difficulty: "easy", description: "Read n, print sum 1+2+...+n", starterCode: "n = int(input())\n", testCases: [{ input: "5\n", expectedOutput: "15" }], points: 10, estimatedMinutes: 10 },
  { title: "Even or Odd", category: "beginner", challengeType: "conditionals", difficulty: "easy", description: "Read n, print Even or Odd", starterCode: "n = int(input())\n", testCases: [{ input: "4\n", expectedOutput: "Even" }, { input: "3\n", expectedOutput: "Odd" }], points: 10, estimatedMinutes: 8 },
  { title: "Count Vowels", category: "beginner", challengeType: "strings", difficulty: "easy", description: "Read string, print vowel count (aeiou)", starterCode: "s = input().lower()\n", testCases: [{ input: "hello\n", expectedOutput: "2" }], points: 15, estimatedMinutes: 12 },
  { title: "Max of Three", category: "beginner", challengeType: "conditionals", difficulty: "easy", description: "Read three ints, print largest", starterCode: "a=int(input());b=int(input());c=int(input())\n", testCases: [{ input: "1\n5\n3\n", expectedOutput: "5" }], points: 15, estimatedMinutes: 12 },
  { title: "Multiplication Table", category: "beginner", challengeType: "loops", difficulty: "easy", description: "Read n, print n*1 through n*5 on separate lines", starterCode: "n = int(input())\n", testCases: [{ input: "3\n", expectedOutput: "3\n6\n9\n12\n15" }], points: 15, estimatedMinutes: 15 },
  { title: "List Sum", category: "beginner", challengeType: "lists", difficulty: "easy", description: "Print sum of [2,4,6,8]", starterCode: "nums = [2,4,6,8]\n", testCases: [{ input: "", expectedOutput: "20" }], points: 10, estimatedMinutes: 8 },
  { title: "First Char Upper", category: "beginner", challengeType: "strings", difficulty: "easy", description: "Read word, print with first letter uppercase", starterCode: "w = input()\n", testCases: [{ input: "python\n", expectedOutput: "Python" }], points: 10, estimatedMinutes: 8 },
  { title: "Factorial", category: "beginner", challengeType: "loops", difficulty: "medium", description: "Read n, print n!", starterCode: "n = int(input())\n", testCases: [{ input: "5\n", expectedOutput: "120" }], points: 20, estimatedMinutes: 15 },
  { title: "FizzBuzz Line", category: "beginner", challengeType: "loops", difficulty: "medium", description: "For i 1..15 print Fizz if div3, Buzz if div5, FizzBuzz if both, else number", starterCode: "for i in range(1, 16):\n    pass\n", testCases: [{ input: "", expectedOutput: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" }], points: 25, estimatedMinutes: 20 },
  { title: "Dictionary Lookup", category: "beginner", challengeType: "dictionaries", difficulty: "easy", description: "Print value for key 'name' in {'name':'Ana','age':20}", starterCode: "user = {'name':'Ana','age':20}\n", testCases: [{ input: "", expectedOutput: "Ana" }], points: 10, estimatedMinutes: 8 },
  { title: "Debug: Fix the Add", category: "beginner", challengeType: "debugging", difficulty: "easy", description: "Fix code to print 8 when adding 5+3", starterCode: "a = 5\nb = '3'\nprint(a + b)\n", testCases: [{ input: "", expectedOutput: "8" }], points: 15, estimatedMinutes: 10 },

  // INTERMEDIATE
  { title: "Palindrome Check", category: "intermediate", challengeType: "strings", difficulty: "medium", description: "Read word, print yes if palindrome else no", starterCode: "w = input().strip().lower()\n", testCases: [{ input: "level\n", expectedOutput: "yes" }, { input: "hello\n", expectedOutput: "no" }], points: 25, estimatedMinutes: 15 },
  { title: "Word Counter", category: "intermediate", challengeType: "strings", difficulty: "medium", description: "Read sentence, print word count", starterCode: "s = input()\n", testCases: [{ input: "hello world\n", expectedOutput: "2" }], points: 20, estimatedMinutes: 12 },
  { title: "CSV Sum Column", category: "intermediate", challengeType: "file-handling", difficulty: "medium", description: "Sum list [10,20,30] and print total", starterCode: "values = [10, 20, 30]\n", testCases: [{ input: "", expectedOutput: "60" }], points: 20, estimatedMinutes: 12 },
  { title: "Safe Divide", category: "intermediate", challengeType: "exceptions", difficulty: "medium", description: "Read a,b; print a//b or 'error' on ZeroDivision", starterCode: "a = int(input())\nb = int(input())\n", testCases: [{ input: "10\n2\n", expectedOutput: "5" }, { input: "1\n0\n", expectedOutput: "error" }], points: 25, estimatedMinutes: 15 },
  { title: "Class Rectangle Area", category: "intermediate", challengeType: "oop", difficulty: "medium", description: "Class Rectangle(w,h) with area(). Print area of 4x5", starterCode: "class Rectangle:\n    def __init__(self, w, h):\n        pass\n", testCases: [{ input: "", expectedOutput: "20" }], points: 30, estimatedMinutes: 20 },
  { title: "JSON Parse", category: "intermediate", challengeType: "json", difficulty: "medium", description: "Parse '{\"x\":9}' and print x", starterCode: "import json\ndata = '{\"x\": 9}'\n", testCases: [{ input: "", expectedOutput: "9" }], points: 20, estimatedMinutes: 12 },
  { title: "Filter Evens", category: "intermediate", challengeType: "lists", difficulty: "medium", description: "From [1,2,3,4,5,6] print evens space-separated", starterCode: "nums = [1,2,3,4,5,6]\n", testCases: [{ input: "", expectedOutput: "2 4 6" }], points: 25, estimatedMinutes: 15 },
  { title: "Fibonacci N", category: "intermediate", challengeType: "algorithms", difficulty: "medium", description: "Read n, print nth Fibonacci (0-index: 0,1,1,2,3...)", starterCode: "n = int(input())\n", testCases: [{ input: "6\n", expectedOutput: "8" }], points: 30, estimatedMinutes: 20 },
  { title: "Generator First N", category: "intermediate", challengeType: "generators", difficulty: "medium", description: "Print list from generator yielding 1..5", starterCode: "def gen():\n    for i in range(1, 6):\n        yield i\n", testCases: [{ input: "", expectedOutput: "[1, 2, 3, 4, 5]" }], points: 25, estimatedMinutes: 15 },
  { title: "API Status Mock", category: "intermediate", challengeType: "apis", difficulty: "easy", description: "Print 200 for status code variable status=200", starterCode: "status = 200\n", testCases: [{ input: "", expectedOutput: "200" }], points: 15, estimatedMinutes: 8 },
  { title: "Output Predict: List Slice", category: "intermediate", challengeType: "output-prediction", difficulty: "easy", description: "Print output of print([1,2,3][1:])", starterCode: "# write print statement\n", testCases: [{ input: "", expectedOutput: "[2, 3]" }], points: 15, estimatedMinutes: 8 },

  // ADVANCED
  { title: "Async Hello", category: "advanced", challengeType: "async", difficulty: "hard", description: "Use asyncio to print async ok", starterCode: "import asyncio\nasync def main():\n    print('async ok')\nasyncio.run(main())\n", testCases: [{ input: "", expectedOutput: "async ok" }], points: 35, estimatedMinutes: 20 },
  { title: "List Comprehension Squares", category: "advanced", challengeType: "algorithms", difficulty: "medium", description: "Print squares of 1-5 as list", starterCode: "# [1,4,9,16,25]\n", testCases: [{ input: "", expectedOutput: "[1, 4, 9, 16, 25]" }], points: 25, estimatedMinutes: 12 },
  { title: "NumPy Mean", category: "advanced", challengeType: "numpy", difficulty: "hard", description: "Print mean of [2,4,6] using numpy or manual 4.0", starterCode: "import numpy as np\narr = np.array([2,4,6])\n", testCases: [{ input: "", expectedOutput: "4.0" }], points: 35, estimatedMinutes: 15 },
  { title: "Pandas Row Count", category: "advanced", challengeType: "pandas", difficulty: "hard", description: "Print 3 for row count of 3 dict rows (simulate)", starterCode: "rows = [{'a':1},{'a':2},{'a':3}]\n", testCases: [{ input: "", expectedOutput: "3" }], points: 30, estimatedMinutes: 15 },
  { title: "Flask Route Mock", category: "advanced", challengeType: "flask", difficulty: "medium", description: "Print 'GET /' for simulated route", starterCode: "route = '/'\nmethod = 'GET'\n", testCases: [{ input: "", expectedOutput: "GET /" }], points: 25, estimatedMinutes: 12 },
  { title: "Sentiment Simple", category: "advanced", challengeType: "ml", difficulty: "medium", description: "Count positive words {good,great} in 'good day'", starterCode: "text = 'good day'\npositive = {'good','great'}\n", testCases: [{ input: "", expectedOutput: "1" }], points: 30, estimatedMinutes: 18 },
  { title: "Thread Safe Counter", category: "advanced", challengeType: "multithreading", difficulty: "hard", description: "Print 5 after simulating counter=5", starterCode: "counter = 5\nprint(counter)\n", testCases: [{ input: "", expectedOutput: "5" }], points: 25, estimatedMinutes: 15 },
  { title: "Mini Project: Grade Book", category: "advanced", challengeType: "mini-project", difficulty: "hard", description: "Average of [80,90,100] print 90.0", starterCode: "scores = [80, 90, 100]\n", testCases: [{ input: "", expectedOutput: "90.0" }], points: 40, estimatedMinutes: 25 },
  { title: "Debug Complex", category: "advanced", challengeType: "debugging", difficulty: "hard", description: "Fix to print 42 from 6*7", starterCode: "a = 6\nb = 7\nprint(str(a) + str(b))\n", testCases: [{ input: "", expectedOutput: "42" }], points: 30, estimatedMinutes: 15 },
  { title: "Data Viz Points", category: "advanced", challengeType: "visualization", difficulty: "medium", description: "Print count of points in [(1,2),(3,4)]", starterCode: "points = [(1,2),(3,4)]\n", testCases: [{ input: "", expectedOutput: "2" }], points: 20, estimatedMinutes: 10 },
];
