/**
 * Knowledge Graph Seed Data
 * Defines concept relationships and prerequisites for Python topics
 */

import KnowledgeGraph from "../models/KnowledgeGraph.js";

const KNOWLEDGE_GRAPH_DATA = [
  // Beginner Topics
  {
    topicKey: "variables",
    displayName: "Variables",
    category: "beginner",
    prerequisites: [],
    dependents: ["data-types", "operators", "conditions"],
    difficulty: 0.2,
    description: "Storing and using data in memory",
    tags: ["basics", "fundamentals"],
  },
  {
    topicKey: "data-types",
    displayName: "Data Types",
    category: "beginner",
    prerequisites: ["variables"],
    dependents: ["operators", "strings", "lists", "dictionaries"],
    difficulty: 0.3,
    description: "Understanding different types of data",
    tags: ["basics", "fundamentals"],
  },
  {
    topicKey: "operators",
    displayName: "Operators",
    category: "beginner",
    prerequisites: ["variables", "data-types"],
    dependents: ["conditions", "loops"],
    difficulty: 0.35,
    description: "Performing operations on data",
    tags: ["basics", "fundamentals"],
  },
  {
    topicKey: "conditions",
    displayName: "Conditions",
    category: "beginner",
    prerequisites: ["variables", "operators"],
    dependents: ["loops", "functions"],
    difficulty: 0.4,
    description: "Making decisions in code",
    tags: ["control-flow", "logic"],
  },
  {
    topicKey: "loops",
    displayName: "Loops",
    category: "beginner",
    prerequisites: ["conditions", "operators"],
    dependents: ["functions", "lists", "strings"],
    difficulty: 0.45,
    description: "Repeating actions efficiently",
    tags: ["control-flow", "iteration"],
  },
  {
    topicKey: "strings",
    displayName: "Strings",
    category: "beginner",
    prerequisites: ["data-types", "loops"],
    dependents: ["functions", "file-handling"],
    difficulty: 0.4,
    description: "Working with text data",
    tags: ["data-structures", "text"],
  },
  {
    topicKey: "lists",
    displayName: "Lists",
    category: "beginner",
    prerequisites: ["data-types", "loops"],
    dependents: ["functions", "dictionaries", "sets"],
    difficulty: 0.45,
    description: "Ordered collections of data",
    tags: ["data-structures", "collections"],
  },
  {
    topicKey: "input-output",
    displayName: "Input & Output",
    category: "beginner",
    prerequisites: ["variables", "strings"],
    dependents: ["file-handling"],
    difficulty: 0.3,
    description: "Getting input and displaying output",
    tags: ["basics", "io"],
  },

  // Intermediate Topics
  {
    topicKey: "functions",
    displayName: "Functions",
    category: "intermediate",
    prerequisites: ["variables", "conditions", "loops"],
    dependents: ["oop", "file-handling", "apis"],
    difficulty: 0.55,
    description: "Reusable blocks of code",
    tags: ["modularity", "organization"],
  },
  {
    topicKey: "tuples",
    displayName: "Tuples",
    category: "intermediate",
    prerequisites: ["lists"],
    dependents: ["dictionaries"],
    difficulty: 0.5,
    description: "Immutable sequences",
    tags: ["data-structures", "collections"],
  },
  {
    topicKey: "dictionaries",
    displayName: "Dictionaries",
    category: "intermediate",
    prerequisites: ["lists", "functions"],
    dependents: ["sets", "apis", "file-handling"],
    difficulty: 0.6,
    description: "Key-value pairs for data",
    tags: ["data-structures", "collections"],
  },
  {
    topicKey: "sets",
    displayName: "Sets",
    category: "intermediate",
    prerequisites: ["lists", "dictionaries"],
    dependents: ["algorithms"],
    difficulty: 0.55,
    description: "Unique collections with operations",
    tags: ["data-structures", "collections"],
  },
  {
    topicKey: "file-handling",
    displayName: "File Handling",
    category: "intermediate",
    prerequisites: ["functions", "strings", "lists"],
    dependents: ["apis", "projects"],
    difficulty: 0.6,
    description: "Reading and writing files",
    tags: ["io", "persistence"],
  },
  {
    topicKey: "error-handling",
    displayName: "Error Handling",
    category: "intermediate",
    prerequisites: ["functions", "conditions"],
    dependents: ["apis", "projects"],
    difficulty: 0.65,
    description: "Managing exceptions gracefully",
    tags: ["robustness", "debugging"],
  },
  {
    topicKey: "modules",
    displayName: "Modules",
    category: "intermediate",
    prerequisites: ["functions"],
    dependents: ["packages", "apis"],
    difficulty: 0.6,
    description: "Organizing code into modules",
    tags: ["organization", "imports"],
  },

  // Advanced Topics
  {
    topicKey: "oop",
    displayName: "Object-Oriented Programming",
    category: "advanced",
    prerequisites: ["functions", "classes"],
    dependents: ["django", "flask", "projects"],
    difficulty: 0.75,
    description: "Classes, objects, and inheritance",
    tags: ["paradigm", "design"],
  },
  {
    topicKey: "classes",
    displayName: "Classes",
    category: "advanced",
    prerequisites: ["functions"],
    dependents: ["oop", "inheritance"],
    difficulty: 0.7,
    description: "Creating custom data types",
    tags: ["oop", "design"],
  },
  {
    topicKey: "inheritance",
    displayName: "Inheritance",
    category: "advanced",
    prerequisites: ["classes"],
    dependents: ["oop", "polymorphism"],
    difficulty: 0.8,
    description: "Reusing and extending classes",
    tags: ["oop", "design"],
  },
  {
    topicKey: "polymorphism",
    displayName: "Polymorphism",
    category: "advanced",
    prerequisites: ["inheritance"],
    dependents: ["design-patterns"],
    difficulty: 0.85,
    description: "Flexible object behavior",
    tags: ["oop", "advanced"],
  },
  {
    topicKey: "decorators",
    displayName: "Decorators",
    category: "advanced",
    prerequisites: ["functions", "classes"],
    dependents: ["flask", "advanced-patterns"],
    difficulty: 0.8,
    description: "Modifying function behavior",
    tags: ["advanced", "meta-programming"],
  },
  {
    topicKey: "generators",
    displayName: "Generators",
    category: "advanced",
    prerequisites: ["functions", "iterators"],
    dependents: ["performance"],
    difficulty: 0.75,
    description: "Lazy evaluation and memory efficiency",
    tags: ["advanced", "performance"],
  },
  {
    topicKey: "iterators",
    displayName: "Iterators",
    category: "advanced",
    prerequisites: ["loops", "functions"],
    dependents: ["generators"],
    difficulty: 0.7,
    description: "Custom iteration protocols",
    tags: ["advanced", "patterns"],
  },
  {
    topicKey: "context-managers",
    displayName: "Context Managers",
    category: "advanced",
    prerequisites: ["classes", "file-handling"],
    dependents: ["resource-management"],
    difficulty: 0.75,
    description: "with statement and resource management",
    tags: ["advanced", "patterns"],
  },

  // APIs & Web
  {
    topicKey: "apis",
    displayName: "APIs",
    category: "advanced",
    prerequisites: ["functions", "file-handling", "error-handling"],
    dependents: ["flask", "django", "web-scraping"],
    difficulty: 0.7,
    description: "Working with web APIs",
    tags: ["web", "networking"],
  },
  {
    topicKey: "flask",
    displayName: "Flask",
    category: "advanced",
    prerequisites: ["functions", "decorators", "apis"],
    dependents: ["web-development", "projects"],
    difficulty: 0.8,
    description: "Lightweight web framework",
    tags: ["web", "framework"],
  },
  {
    topicKey: "django",
    displayName: "Django",
    category: "advanced",
    prerequisites: ["oop", "apis", "orm"],
    dependents: ["web-development", "projects"],
    difficulty: 0.85,
    description: "Full-featured web framework",
    tags: ["web", "framework", "mvc"],
  },
  {
    topicKey: "orm",
    displayName: "ORM",
    category: "advanced",
    prerequisites: ["oop", "databases"],
    dependents: ["django", "flask-sqlalchemy"],
    difficulty: 0.8,
    description: "Object-relational mapping",
    tags: ["database", "abstraction"],
  },
  {
    topicKey: "web-scraping",
    displayName: "Web Scraping",
    category: "advanced",
    prerequisites: ["apis", "html-parsing"],
    dependents: ["data-collection", "projects"],
    difficulty: 0.75,
    description: "Extracting data from websites",
    tags: ["web", "data"],
  },

  // Data Science
  {
    topicKey: "numpy",
    displayName: "NumPy",
    category: "advanced",
    prerequisites: ["lists", "functions", "math"],
    dependents: ["pandas", "data-science"],
    difficulty: 0.75,
    description: "Numerical computing in Python",
    tags: ["data-science", "numerical"],
  },
  {
    topicKey: "pandas",
    displayName: "Pandas",
    category: "advanced",
    prerequisites: ["numpy", "dictionaries", "data-analysis"],
    dependents: ["data-science", "machine-learning"],
    difficulty: 0.8,
    description: "Data manipulation and analysis",
    tags: ["data-science", "analysis"],
  },
  {
    topicKey: "data-analysis",
    displayName: "Data Analysis",
    category: "advanced",
    prerequisites: ["pandas", "statistics"],
    dependents: ["machine-learning", "visualization"],
    difficulty: 0.8,
    description: "Analyzing and interpreting data",
    tags: ["data-science", "analytics"],
  },
  {
    topicKey: "visualization",
    displayName: "Data Visualization",
    category: "advanced",
    prerequisites: ["pandas", "matplotlib"],
    dependents: ["data-science", "reporting"],
    difficulty: 0.75,
    description: "Creating charts and graphs",
    tags: ["data-science", "visualization"],
  },

  // Additional foundational topics
  {
    topicKey: "math",
    displayName: "Math Operations",
    category: "beginner",
    prerequisites: ["operators"],
    dependents: ["numpy", "algorithms"],
    difficulty: 0.35,
    description: "Mathematical functions and operations",
    tags: ["basics", "math"],
  },
  {
    topicKey: "algorithms",
    displayName: "Algorithms",
    category: "advanced",
    prerequisites: ["loops", "conditions", "sets"],
    dependents: ["data-structures", "performance"],
    difficulty: 0.85,
    description: "Problem-solving patterns",
    tags: ["advanced", "computer-science"],
  },
  {
    topicKey: "data-structures",
    displayName: "Data Structures",
    category: "intermediate",
    prerequisites: ["lists", "dictionaries", "sets"],
    dependents: ["algorithms", "performance"],
    difficulty: 0.7,
    description: "Efficient data organization",
    tags: ["intermediate", "computer-science"],
  },
  {
    topicKey: "performance",
    displayName: "Performance Optimization",
    category: "advanced",
    prerequisites: ["algorithms", "generators"],
    dependents: ["advanced-patterns"],
    difficulty: 0.9,
    description: "Writing efficient code",
    tags: ["advanced", "optimization"],
  },
  {
    topicKey: "databases",
    displayName: "Databases",
    category: "intermediate",
    prerequisites: ["file-handling", "sql"],
    dependents: ["orm", "django"],
    difficulty: 0.7,
    description: "Working with databases",
    tags: ["data", "persistence"],
  },
  {
    topicKey: "sql",
    displayName: "SQL",
    category: "intermediate",
    prerequisites: ["data-types", "logic"],
    dependents: ["databases", "orm"],
    difficulty: 0.65,
    description: "Structured query language",
    tags: ["database", "query"],
  },
  {
    topicKey: "testing",
    displayName: "Testing",
    category: "intermediate",
    prerequisites: ["functions", "conditions"],
    dependents: ["quality-assurance", "projects"],
    difficulty: 0.6,
    description: "Writing and running tests",
    tags: ["quality", "testing"],
  },
  {
    topicKey: "debugging",
    displayName: "Debugging",
    category: "intermediate",
    prerequisites: ["error-handling", "testing"],
    dependents: ["quality-assurance"],
    difficulty: 0.65,
    description: "Finding and fixing bugs",
    tags: ["quality", "debugging"],
  },
];

export async function seedKnowledgeGraph() {
  console.log("Seeding knowledge graph...");

  for (const topic of KNOWLEDGE_GRAPH_DATA) {
    await KnowledgeGraph.findOneAndUpdate(
      { topicKey: topic.topicKey },
      topic,
      { upsert: true, new: true }
    );
  }

  console.log(`Seeded ${KNOWLEDGE_GRAPH_DATA.length} topics in knowledge graph`);
}

export default KNOWLEDGE_GRAPH_DATA;
