"""
Django settings for python_edition_django project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from backend/.env (existing behavior)
load_dotenv(BASE_DIR.parent / ".env")
# Also attempt to load project-root .env for local development
try:
    load_dotenv(BASE_DIR.parent.parent / ".env")
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").strip().lower() in ("1", "true", "yes")

APPEND_SLASH = True

# Read ALLOWED_HOSTS from environment variable (comma-separated list)
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()] if _allowed_hosts_env else []
ALLOWED_HOSTS += ["localhost", "127.0.0.1"]
# Also allow all Render subdomains automatically
ALLOWED_HOSTS += [".onrender.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'users',
    'lessons.apps.LessonsConfig',
    'assessments',
    'ai_engine',
    'recommendation',
    'analytics',
    'gamification',
    'evaluation',
    # 'django_q',
    'rest_framework_simplejwt',
]

PGVECTOR_ENABLED = os.getenv("PGVECTOR_ENABLED", "false").strip().lower() in ("1", "true", "yes")

if PGVECTOR_ENABLED:
    INSTALLED_APPS.append('pgvector')

AUTH_USER_MODEL = 'core.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware', # Ensured CorsMiddleware is present
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Base CORS/CSRF origins (always included)
_BASE_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
]

# Read extra origins from environment variable (comma-separated)
_cors_env = os.getenv("CORS_ALLOWED_ORIGINS", "")
_extra_origins = [o.strip() for o in _cors_env.split(",") if o.strip()] if _cors_env else []

CORS_ALLOWED_ORIGINS = _BASE_ORIGINS + _extra_origins

# Allow all *.onrender.com origins automatically
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.onrender\.com$",
    r"^https://.*\.vercel\.app$",
]

cors_allow_all = os.getenv("CORS_ALLOW_ALL_ORIGINS", "")
if cors_allow_all:
    CORS_ALLOW_ALL_ORIGINS = cors_allow_all.strip().lower() in ("1", "true", "yes")
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

CORS_ALLOW_CREDENTIALS = True

# Read extra CSRF origins from environment variable (comma-separated)
_csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "")
_extra_csrf = [o.strip() for o in _csrf_env.split(",") if o.strip()] if _csrf_env else []

CSRF_TRUSTED_ORIGINS = _BASE_ORIGINS + _extra_csrf + _extra_origins


ROOT_URLCONF = 'python_edition_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'python_edition_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Dynamically determine conn_max_age to prevent Supabase connection pooling lockups.
# Transaction pooler (port 6543) requires conn_max_age = 0.
db_url = os.getenv("DATABASE_URL", "")
default_conn_max_age = 0 if ("supabase" in db_url or "6543" in db_url or "pgbouncer" in db_url or "postgres" in db_url) else 600
conn_max_age_val = int(os.getenv("CONN_MAX_AGE", default_conn_max_age))

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR}/db.sqlite3"),
        conn_max_age=conn_max_age_val,
    )
}

# If using local environment variables for Postgres instead of DATABASE_URL
if not os.getenv("DATABASE_URL") and os.getenv("DB_ENGINE"):
    DATABASES["default"] = {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME", "python_edition_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD") or ("The_renu@28" if DEBUG else ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'core.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if not DEBUG:
    WHITENOISE_USE_FINDERS = True
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "true").strip().lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '120/minute',
        'ai': '20/minute',
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "adaptive-cache",
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "ai_engine.embeddings": {
            "handlers": ["console"],
            "level": os.getenv("EMBEDDING_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "recommendation.engine": {
            "handlers": ["console"],
            "level": os.getenv("RECOMMENDATION_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "evaluation.metrics": {
            "handlers": ["console"],
            "level": os.getenv("EVALUATION_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

Q_CLUSTER = {
    "name": os.getenv("Q_CLUSTER_NAME", "adaptive-embeddings"),
    "workers": int(os.getenv("Q_WORKERS", "4")),
    "timeout": int(os.getenv("Q_TIMEOUT", "120")),
    "retry": int(os.getenv("Q_RETRY", "180")),
    "queue_limit": int(os.getenv("Q_QUEUE_LIMIT", "500")),
    "orm": "default",
}
