# Generated by Django 6.0.4 on 2026-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_certificate_verification_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module_id', 'order'], name='lessons_module__1db223_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module_id', 'difficulty'], name='lessons_module__353faf_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user_id', 'lesson_id'], name='user_progre_user_id_2463b9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user_id', 'completed'], name='user_progre_user_id_2c0065_idx'),
        ),
    ]
