# Generated by Django 6.0.4 on 2026-05-25 07:44

from django.db import migrations

def fix_curriculum_live(apps, schema_editor):
    Module = apps.get_model('core', 'Module')
    Lesson = apps.get_model('core', 'Lesson')
    
    # Delete all existing modules and lessons to clean up the '0 to 9' mess
    Module.objects.all().delete()
    Lesson.objects.all().delete()
    
    modules_data = [
        ('mod-python-basics', 1, 'Python Basics', 'Master the fundamentals of Python.'),
        ('mod-data-types', 2, 'Data Types', 'Deep dive into Python data structures.'),
        ('mod-control-flow', 3, 'Control Flow', 'Learn if-else, loops, and logic.'),
        ('mod-functions', 4, 'Functions', 'Reusable code blocks and scope.'),
        ('mod-modules-packages', 5, 'Modules & Packages', 'Organizing code into files.'),
        ('mod-file-handling', 6, 'File Handling', 'Reading and writing files.'),
        ('mod-error-handling', 7, 'Error Handling', 'Try, except, and robust code.'),
        ('mod-oop', 8, 'OOP', 'Classes, objects, and inheritance.'),
        ('mod-advanced-python', 9, 'Advanced Python', 'Generators, decorators, context managers.'),
        ('mod-real-world-projects', 10, 'Real-world Projects', 'Apply everything to build projects.'),
    ]
    
    for mod_id, order, title, desc in modules_data:
        Module.objects.create(
            id=mod_id,
            title=title,
            description=desc,
            order=order,
            image_url='https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80'
        )
        
        for i in range(1, 11):
            for difficulty in ['Beginner', 'Intermediate', 'Pro']:
                les_id = f"les-{mod_id.replace('mod-', '')}-{i}-{difficulty.lower()}"
                les_title = f"{title} Lesson {i} ({difficulty})"
                
                content = f"""# {les_title}

## 📖 Definition
Welcome to {les_title}! This lesson is part of the **{title}** module. 
At the **{difficulty}** level, it's crucial to understand the foundational principles of this topic. 
Python provides powerful built-in capabilities to handle {title.lower()} efficiently.

## 💡 Example
Imagine you are building a real-world application. Understanding {title.lower()} allows you to solve complex problems with minimal lines of code.

## ⚙️ Syntax
```python
# Basic syntax for {title.lower()}
def example_{title.replace(' ', '_').lower()}():
    pass
```

## 💻 Example Code
```python
# Here is a practical implementation
print('Welcome to {les_title}!')

# A simple loop or logic block
for i in range(3):
    print(f'{les_title} iteration', i)
```

## 🧠 Knowledge Check
- Did you understand the syntax?
- Can you apply {title.lower()} in a real-world scenario?
- Try modifying the example code to see how the output changes.

## 🏆 Challenge
Test your skills! Move to the Challenge runner on this page and complete the assigned task to earn points and prove your mastery.
"""
                Lesson.objects.create(
                    id=les_id,
                    module_id=mod_id,
                    title=les_title,
                    content=content,
                    order=i,
                    difficulty=difficulty,
                    duration=15,
                    slug=f"{title.replace(' ', '-').lower()}-lesson-{i}-{difficulty.lower()}"
                )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_lesson_lessons_module__1db223_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_curriculum_live),
    ]
