# Generated by Django 6.0.4 on 2026-05-25 07:58

from django.db import migrations

def delete_all_curriculum(apps, schema_editor):
    Module = apps.get_model('core', 'Module')
    Lesson = apps.get_model('core', 'Lesson')
    
    # User requested to delete all modules to start from start again
    Module.objects.all().delete()
    Lesson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_fix_curriculum_live'),
    ]

    operations = [
        migrations.RunPython(delete_all_curriculum),
    ]
